### ISSUE TITLE
Refactor CLI with traits and into separate crate

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain#79]
Refactor the Trustchain CLI given #72:
- [x] Move Trustchain CLI into separate crate `trustchain-cli`
- [x] Construct traits (`TrustchainDIDCLI` and `TrustchainVCCLI`) for DID and VC functionality (#72)
- [x] Implement traits for `TrustchainCLI` struct
- [x] Merge `trustchain-ffi` crate from with `gui` and `mobile` modules from #62 and #63
- [x] Add functions to be implemented for `gui` and `mobile` given #72 
- [ ] Confirm both CLI traits' methods

**Comment by sgreenbury** [comment]
- [ ] Comment out todo methods of the API
- [ ] Remove `trustchain-api` dep on trustchain-ion:
  - [ ] Trait without default impl
  - [ ] Impl separately in CLI and FFI crates for local structs?

**Comment by sgreenbury** [comment]
Following consideration, `trustchain-api` remains downstream of `trustchain-ion`. Reconsider in further API refinements associated with #37.
